### ISSUE TITLE
how to launch in production ?

### ISSUE THREAD

**Issue by nacimgoura** [eko/docker-symfony#106]
Hello,
thank you for this project.
I want to launch it in production on a server but it still runs in the dev environment.
How do I tell him I'm in a production environment?

**Comment by karael** [comment]
do not use docker-compose in production

**Comment by eko** [comment]
You should not use docker-compose in production because this is not the best practice: docker-compose is more a development utility tool to allow developers managing all the project tools and applications on a single machine.

You should set up a container orchestrator such as Kubernetes or Docker Swarm or make your containers run in the cloud via providers solutions (AWS, GCP, Heroku, DigitalOcean, ...). These tools will allow you to scale your application better than using docker-compose.

Thank you.
