### ISSUE TITLE
Error with php version

### ISSUE THREAD

**Issue by davidt22** [eko/docker-symfony#119]
Hi, there is an error when accesing to website:

`Fatal Error: composer.lock was created for PHP version 7.3 or higher but the current PHP version is 7.2.22.`

Can you fix it, please ?
Thanks

**Comment by eko** [comment]
Hi @davidt22,

Have you checked out the repository recently? Because the Dockerfiles specify a alpine:3.10 version and the corresponding PHP versions are 7.3.11-r0, see: https://pkgs.alpinelinux.org/packages?name=php7-fpm&branch=v3.10

I don’t think there is an issue here, it works for me. Could you double check please?

**Comment by florianproxi** [comment]
Hi, i have the same problem. In cmd when i put php -v it says php 7.1

**Comment by Hiroki-IT** [comment]
@davidt22 
@florianproxi 

Hello!!

I had the same problem, but solved it in the following steps.  :smiley:

I'm sorry that it's hard to read, because I'm not good at English. :sweat:

1. To define the following in ```config``` of your composer.json

```
"config": {
    "platform": {
        "php": "7.2.22"
}
```

2. To delete your composer.lock.

3. To execute ```composer install```.

4. To try ```http://symfony.localhost```.

I hope you will go well. :thumbsup:

**Comment by eko** [comment]
Thank you for helping each other with this issue 👍 :)

Closing this now

**Comment by Kaesthenics** [comment]
Thank you very much from france!!!

**Comment by cluis13915** [comment]
I solved it switching the Apache PHP version.

```
sudo a2dismod php7.1
sudo a2enmod php7.2
sudo systemctl restart apache2
```

**Comment by janitzed** [comment]
Fatal Error: composer.lock was created for PHP version 7.4 or higher but the current PHP version is 7.3.23.

**Comment by janitzed** [comment]
Have this error

Fatal Error: composer.lock was created for PHP version 7.4 or higher but the current PHP version is 7.3.23.

I have try:

1)
sudo rm -rf /etc/php/7.1
sudo rm -rf /etc/php/7.2
sudo rm -rf /etc/php/7.3
sudo rm -rf /etc/php/8.0
sudo systemctl restart apache2

2)
rm composer.lock
composer update

3)
rm composer.lock
rm -rf vendor
composer install
sudo systemctl restart apache2

4) Finally it works for me

sudo a2dismod php7.1
sudo a2dismod php7.2
sudo a2dismod php7.3
sudo a2dismod php8.0

sudo a2enmod php7.4

sudo systemctl restart apache2
