### ISSUE TITLE
Some tools for the PHP container

### ISSUE THREAD

**Issue by automatix** [eko/docker-symfony#142]
Hello @eko,

In the daily work it's comfortable to have following tools on the server / in the container:

- Composer (PR  #139)
- Symfony CLI (PR #140)
- Yarn and for its working Node.js and npm (PR #141)

Please be so kind and review & approve the PRs above. Thank you!

**Comment by riwiki** [comment]
Hi @automatix,
I had a look at your PRs. Can I suggest a different approach?
Instead of adding the tools directly to the php container, I usually add such tools to a dev container that extends the php container. Thereby, I keep the php container clean from tools and smaller for production.
I haven't done a lot with docker-compose, but I liked that pattern the times I did. If it sounds interesting, I am happy to make a PR.
Cheers

**Comment by eko** [comment]
Hi @riwiki,

I just merged the PR for adding the tools in the PHP container but I agree with you that this approach would be better. Feel free to submit a PR :-)

Thank you all

**Comment by ricfio** [comment]
Hi @riwiki, Hi @eko,
I agree that using an external development container to install the various tools is a better approach
... so I look forward to the corresponding PR !

**Comment by automatix** [comment]
Hi guys!

@riwiki In principle I agree with you. My suggestion is just a quick solution.

@eko Thank you very much for the merges!

The ticket is resolved. I'm closing it.
