### ISSUE TITLE
Symfony 4 database config

### ISSUE THREAD

**Issue by 80jan** [eko/docker-symfony#69]
How configure database in SF4?

**Comment by R-Romanov** [comment]
Firstly, u need to install Doctrine: https://symfony.com/doc/current/doctrine.html

**Comment by makoso** [comment]
Via .env file in main catalog of your application:
https://symfony.com/doc/current/doctrine.html#configuring-the-database

**Comment by pedramham** [comment]
where is .env ??? i can not find????????????

**Comment by eko** [comment]
Hello,

`.env` file has to be located into Symfony project, as specified by @makoso as environment variables written in this file will be related to Symfony only.

Sorry but this issue is not related to `docker-symfony` repository so I will close it.

Do not hesitate to continue exchanging on this issue by the way if it's needed.

Thank you
